### PR TITLE
Fix capitalization in service fee query (id 4017925)

### PR DESCRIPTION
**Pull request by harisang**
Trivial PR that lowercases the service fee query and uses snake case throughout for column names (4017925)

### CODE REVIEW

**Comment by harisang** [comment]
@fhenneke In case you have other stylistic suggestions, this might be the PR to apply them. E.g, column names. Should we use underscores and lowercase letters instead of names such as `bondingPool` ?

**Comment by harisang** [comment]
> @fhenneke In case you have other stylistic suggestions, this might be the PR to apply them. E.g, column names. Should we use underscores and lowercase letters instead of names such as `bondingPool` ?

Actually pushed a change to snake case throughout

**Comment by harisang** [comment]
> LGTM, what's the reason for removing capitalization? I thought capitalizing SQL specific words was the standard syntax.

Yeah that's a valid point. I guess currently we are inconsistent and i decided to propose going with lower case. Whatever we choose, it would be nice to stick to it.

Do you have any preference @fhenneke ?

**Comment by fhenneke** [comment]
I do not really have an opinion on capitalization. The most important part to me would be would be that it is consistens (first within a query and then across queries).

If we cafe about a specific styling, we can add it to the linting check, e.g. via
```
[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower
```

**Comment by harisang** [comment]
Ok, i would suggest we keep this as is then (lower case) and try to be consistent throughout. Merging so that we can finally start fixing the query

**Pull request merged**
