### PR TITLE
Update reduced bonding pools in service fees query

### PR DESCRIPTION
**Pull request by bram-vdberg**
This PR updates the reduced bonding pools in the service fees query after #58

### CODE REVIEW

**Review by harisang — CHANGES_REQUESTED** [review]
Could you follow the format we use for the rest of the reduced bonding pools? There are additional entries such as solver name, joined_on etc and the pool_name has so far been set to 'Reduced-Bonding'. We can of course reevaluate that but it would need to be uniform over all subpools

**Comment by harisang** [comment]
If you look at the previous entries, we have the exact name with the environment included, e.g, prod-Barter, barn-Barter etc. Not sure if it is really needed anywhere, but could you follow that format to avoid having something break?

**Comment by bram-vdberg** [comment]
I updated the pool names to show prod/barn. I also renamed Furucombo to Portus to be in line with their rebranding.

**Review by fleupold — APPROVED** [review]

**Comment by harisang** [comment]
The query is still not uniform and new entries don't follow the already used naming conventions.

image

**Comment by harisang** [comment]
@bram-vdberg Took the initiative to push a commit myself as i believe this is currently causing issues with today's payouts (since we switched colocated Rizzolver on yesterday). Could you have a quick look? Thanks!

**Review by bram-vdberg — COMMENTED** [review]
LGTM, I ran the query on Dune as a test: https://dune.com/queries/4246690. I noticed prod-Portus and prod-Fractal are listed even though they're not live yet, I assume that's not a problem.

**Review by harisang — APPROVED** [review]

**Pull request merged**
